version: "3.3"

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      DATABASE_URL: "postgres://contact_graph:contact_graph@db/contact_graph"
      FLASK_ENV: "development"
      FLASK_RUN_HOST: "0.0.0.0"
      FLASK_DEBUG: 1
    ports:
      - "8000:8000"

  db:
    image: postgres:11
    environment:
      POSTGRES_USER: contact_graph
      POSTGRES_PASSWORD: contact_graph
      PSOTGRES_DB: contact_graph
    volumes:
      - "data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"

volumes:
  data:
