"""Add submitted_at field

Revision ID: 0ef4d2960cc0
Revises: 573a0496fe7a
Create Date: 2020-04-10 14:08:13.119796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ef4d2960cc0'
down_revision = '573a0496fe7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('submitted_at', sa.DateTime(), nullable=True))
    op.alter_column('contact', 'key',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('positive', sa.Column('submitted_at', sa.DateTime(), nullable=True))
    op.alter_column('positive', 'key',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('positive', 'key',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('positive', 'submitted_at')
    op.alter_column('contact', 'key',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('contact', 'submitted_at')
    # ### end Alembic commands ###
